cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from . import views
import cpovc_auth
import cpovc_access
from django.urls import include, path, re_path
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_registry import views as registry_views

from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_ovc import urls as ovc_urls
from cpovc_settings import urls as settings_urls
from cpovc_manage import urls as manage_urls
from cpovc_help import urls as help_urls
from notifications import urls as noti_urls
from cpovc_ctip import urls as ctip_urls
from cpovc_afc import urls as ac_urls

from django.views.generic import TemplateView
# For dashboard
from cpovc_dashboard import urls as dashboard_api_urls
from cpovc_dashboard import views as dash_views


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$', 'cpovc_auth.views.log_in', name='home'),
    path('', views.home, name='home'),
    path('accounts/request/', views.access, name='access'),
    path('accounts/terms/<int:id>/', cpovc_access.views.terms,
         name='terms'),
    path('register/', cpovc_auth.views.register, name='register'),
    path('auth/', include(auth_urls)),
    path('registry/', include(registry_urls)),
    path('forms/', include(forms_urls)),
    path('reports/', include(reports_urls)),
    path('gis/', include(gis_urls)),
    path('api/v1/', include(api_urls)),
    path('ovc_care/', include(ovc_urls)),
    path('settings/', include(settings_urls)),
    path('manage/', include(manage_urls)),
    path('help/', include(help_urls)),
    path('forms/ctip/', include(ctip_urls)),
    path('forms/altcare/', include(ac_urls)),
    path('notifications/', include(noti_urls, namespace='notifications')),
    re_path(r'^dashboard/(?P<did>[A-Z{2}]+)/$',
            registry_views.dashboard, name='dashboard'),
    # Accounts management
    path('accounts/', include(cpovc_auth.urls)),
    # Override Login and Logout not to use the /accounts/*
    path('login/', cpovc_auth.views.log_in, name='login'),
    path('logout/', cpovc_auth.views.log_out, name='logout'),
    path('d/', dash_views.ovc_dashboard, name='ovc_dashboard'),
    re_path(r'^api/v2/', include(dashboard_api_urls)),
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                                   content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

cpovc_afc/urls.py
from django.urls import path, re_path
from . import views

# This should contain urls related to Care reforms ONLY
urlpatterns = [
    path('', views.alt_care_home, name='alternative_care'),
    path(
        'new/<uuid:case_id>/', views.new_alternative_care,
        name='new_alt_care'),
    path(
        'view/<uuid:care_id>/', views.view_alternative_care,
        name='view_alt_care'),
    path(
        'edit/<uuid:care_id>/', views.edit_alternative_care,
        name='edit_alt_care'),
    re_path(r'^(?P<cid>[A-Z{2}]+)/(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<care_id>[0-9A-Za-z_\-{32}]+)/$',
            views.alt_care_form, name='alt_care_form'),
    re_path(r'^(?P<cid>[A-Z{2}]+)/(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<care_id>[0-9A-Za-z_\-{32}]+)/(?P<ev_id>\d+)/$',
            views.edit_alt_care_form, name='edit_alt_care_form'),
    re_path(r'^(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<event_id>[0-9A-Za-z_\-{32}]+)/$',
            views.delete_alt_care_form, name='delete_alt_care_form'),
]

cpovc_ctip/urls.py
from django.urls import path, re_path
from . import views

# This should contain urls related to CTiP ONLY
urlpatterns = [
    path('', views.ctip_home, name='ctip_home'),
    re_path(r'^case/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$', views.view_ctip_case, name='view_ctip_case'),
    re_path(r'^form/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/(?P<id>\d+)/$',
            views.ctip_forms, name='ctip_forms'),
    re_path(r'^form/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$',
            views.ctip_form, name='ctip_form'),
    re_path(r'^form/view/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$',
            views.view_ctip_form, name='view_ctip_form'),
    path('new/<uuid:case_id>/', views.new_ctip_case, name='new_ctip_case'),
    path('edit/<uuid:case_id>/', views.edit_ctip_case, name='edit_ctip_case'),
]

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion
# pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.notifications_home, name='home'),
    pattern(r'^(?P<id>\d+)/$', views.notifications_read, name='read'),
    pattern(r'^all/$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

cpovc_afc/models.py
import uuid
from django.db import models
from django.utils import timezone

from cpovc_registry.models import RegPerson, RegOrgUnit
from cpovc_forms.models import OVCCaseRecord
from cpovc_auth.models import AppUser


class AFCMain(models.Model):
    care_id = models.UUIDField(
        primary_key=True, default=uuid.uuid1, editable=False)
    case = models.ForeignKey(OVCCaseRecord, on_delete=models.CASCADE)
    case_number = models.CharField(max_length=12, blank=True)
    care_type = models.CharField(max_length=5, null=True, blank=True)
    care_sub_type = models.CharField(max_length=5, null=True, blank=True)
    person = models.ForeignKey(RegPerson, on_delete=models.CASCADE)
    school_level = models.CharField(max_length=4, null=True)
    immunization_status = models.CharField(max_length=4, null=True)
    org_unit = models.ForeignKey(RegOrgUnit, on_delete=models.CASCADE)
    case_status = models.BooleanField(null=True, default=None)
    case_stage = models.IntegerField(default=0)
    case_date = models.DateField()
    created_by = models.ForeignKey(
        AppUser, blank=True, on_delete=models.CASCADE)
    timestamp_created = models.DateTimeField(default=timezone.now)
    timestamp_modified = models.DateTimeField(default=timezone.now)
    is_void = models.BooleanField(default=False)

    def _get_cases(self):
        _cases = AFCMain.objects.all().count()
        if self.case_number:
            return _cases
        else:
            return _cases + 1

    def save(self, *args, **kwargs):
        # This is to save the Unique code.
        if self.pk is None and not self.case_number:
            self.case_number = self.case_number
        elif self.pk and not self.case_number:
            case_num = self._get_cases()
            self.case_number = case_num

        # Call the original save method
        super(AFCMain, self).save(*args, **kwargs)

    class Meta:
        db_table = 'ovc_afc_main'
        verbose_name = 'Alternative Care'
        verbose_name_plural = 'Alternative Cares'

    def __unicode__(self):
        """To be returned by admin actions."""
        return '%s - %s' % (str(self.case_number), str(self.case))


class AFCEvents(models.Model):
    event_id = models.UUIDField(
        primary_key=True, default=uuid.uuid1, editable=False)
    case = models.ForeignKey(OVCCaseRecord, on_delete=models.CASCADE)
    care = models.ForeignKey(AFCMain, on_delete=models.CASCADE)
    event_count = models.IntegerField(default=1)
    event_date = models.DateField()
    form_id = models.CharField(max_length=3, blank=True)
    person = models.ForeignKey(RegPerson, on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        AppUser, blank=True, on_delete=models.CASCADE)
    timestamp_created = models.DateTimeField(default=timezone.now)
    timestamp_modified = models.DateTimeField(default=timezone.now)
    is_void = models.BooleanField(default=False)

    class Meta:
        db_table = 'ovc_afc_event'
        verbose_name = 'AFC Event'
        verbose_name_plural = 'AFC Events'

    def __unicode__(self):
        """To be returned by admin actions."""
        return '%s' % (str(self.case))


class AFCForms(models.Model):
    form_id = models.UUIDField(
        primary_key=True, default=uuid.uuid1, editable=False)
    event = models.ForeignKey(AFCEvents, on_delete=models.CASCADE)
    question_id = models.CharField(max_length=12)
    item_value = models.CharField(max_length=5)
    item_detail = models.TextField(null=True, blank=True)
    timestamp_created = models.DateTimeField(default=timezone.now)
    timestamp_modified = models.DateTimeField(default=timezone.now)
    is_void = models.BooleanField(default=False)

    class Meta:
        db_table = 'ovc_afc_form'
        verbose_name = 'AFC Form data'
        verbose_name_plural = 'AFC Forms data'

    def __unicode__(self):
        """To be returned by admin actions."""
        return '%s' % (str(self.event))


class AFCInfo(models.Model):
    info_id = models.UUIDField(
        primary_key=True, default=uuid.uuid1, editable=False)
    care = models.ForeignKey(AFCMain, on_delete=models.CASCADE)
    person = models.ForeignKey(RegPerson, on_delete=models.CASCADE)
    item_id = models.CharField(max_length=12)
    item_value = models.CharField(max_length=10)
    item_detail = models.TextField(null=True, blank=True)
    timestamp_created = models.DateTimeField(default=timezone.now)
    timestamp_modified = models.DateTimeField(default=timezone.now)
    is_void = models.BooleanField(default=False)

    class Meta:
        db_table = 'ovc_afc_info'
        verbose_name = 'AFC Form Info'
        verbose_name_plural = 'AFC Forms Infos'

    def __unicode__(self):
        """To be returned by admin actions."""
        return '%s' % (str(self.care))


class AFCQuestions(models.Model):
    """List of questions used by forms."""

    question_text = models.TextField(null=True, blank=True)
    question_code = models.CharField(max_length=50)
    form_id = models.CharField(max_length=4, null=True, blank=True)
    answer_type_id = models.CharField(max_length=4, null=True, blank=True)
    answer_set_id = models.IntegerField(db_index=True, null=True)
    the_order = models.IntegerField(db_index=True, null=True)
    timestamp_created = models.DateTimeField(auto_now=True, null=True)
    timestamp_updated = models.DateTimeField(auto_now=True, null=True)
    is_void = models.BooleanField(default=False)

    class Meta:
        """Override some params."""

        db_table = 'ovc_afc_questions'
        verbose_name = 'AFC Question'
        verbose_name_plural = 'AFC Questions'

    def __unicode__(self):
        """To be returned by admin actions."""
        return '%s' % (str(self.question_code))

templates/management/dq_home.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %} CPIMS Data Quality Management {% endblock %}

{% load app_filters %}

{% load crispy_forms_tags %}

{% block style_code %}
<link href="{% static 'plugins/datatables/css/data-table.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/bootstrap-datepicker/css/datepicker3.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet" />
<style type="text/css">
    
table.display {
    width: 100%;
    margin: 0;
}
.dataTables_length{
    margin-right: 50px;
}


</style>
{% endblock %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">Data Quality Management</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header"> CPIMS Management <small>Home</small></h1>
<!-- end page-header -->
<div id="messages" class="alert alert-danger fade in" style="display: none;" tabindex="1">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <span class="invalid-form-message" id="invalid-form-message"></span>
</div>
<!-- begin row -->
<div class="row">
  <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>                      
                <h4 class="panel-title">Data Quality Management</h4>
            </div>
            <!-- start panel body -->
            <div class="panel-body">
                <form id="dqcases" method="POST" action=".">
                    {% csrf_token %}
                    <div class="row">
                    
                    <div class="col-md-6">

                        <div class="form-group">
                        <label for="aspect">Data Quality Aspect</label>
                        <select class="form-control" id="q_aspect" name="q_aspect" />
                           <option value="">All</option>
                           <option value="1"> Missing DoB / Invalid DoB</option>
                           <option value="2"> Age inappropriate cases</option>
                           <option value="3"> Gender incompatible cases</option>
                           <option value="4"> Missing Intervention (Pending Cases)</option>

                        </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                        <label for="variance">Age Variance</label>
                        <select class="form-control" id="variance" name="variance" />
                           <option value="">Any</option>
                           <option value="1"> Equal to (=)</option>
                           <option value="2"> Greater than (>)</option>
                           <option value="3"> Less than (<)</option>
                        </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                        <label for="age">Age</label>
                        <input class="form-control" type="number" name="age" id="age">
                        </div>
                    </div>
                </div>
                <div class="row">
                    
                    <div class="col-md-6">
                        <div class="form-group">
                        <label for="age">Organization Unit</label>
                        {{ form.org_unit }}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                        <label for="age">Date from </label>
                        {{ form.report_from_date }}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                        <label for="age">To date</label>
                        {{ form.report_to_date }}
                        </div>
                    </div>
                </div>
                <div class="row">                    
                    <div class="col-md-12">
                        <button type="button" class="btn btn-sm btn-primary m-r-5 ddash"> Filter </button>
                        <button type="reset" class="btn btn-sm btn-default"> Reset </button>
                        <span id="mng_messages">Please note changes to the children and cases will be available on DQ Module and data portal after midnight today.</span>
                    </div>
                </div>
                </form>
                <hr>
                <div class="row">

                    <div class="col-md-12">
                        <table id="data-table" class="table table-striped table-bordered table-td-valign-middle" width="100%">
                        <thead>
                        <tr>
                        <th>#</th>
                        <th>Case Date</th>
                        <th>CPIMS ID</th>
                        <th>Name / Initials</th>
                        <th>DOB</th>
                        <th>Sex</th>
                        <th>Age</th>                        
                        <th>Case Category</th>
                        <th>Org Unit</th>
                        <th>Case Status</th>
                        <th width="30%">Intervention</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <!-- end panel body -->
        </div>
        <!-- end panel -->  
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->

{% endblock %}

{% block lazy_javascript_code %}
<script src="{% static 'plugins/datatables/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/select2/dist/js/select2.min.js' %}"></script>
<script src="{% static 'plugins/datatables/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/datatables/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'js/buttons.html5.min.js' %}"></script>

<script>
$(document).ready(function() {
    $('#from_date, #to_date').datepicker({
        dateFormat: 'yy-mm-dd', format: 'dd-M-yyyy',
        endDate: '+0d', enddate: '+0d', autoclose: true
    });

    $("#id_org_unit").select2();


    $('.ddash').on('click', function(ev) {
        // var hashValue = location.hash.replace(/^#/, '');
        var id = $(this).attr('id');
        var q_aspect = $( "#q_aspect" ).val();
        var variance = $( "#variance" ).val();
        var age = $( "#age" ).val();
        var from_date = $( "#from_date" ).val();
        var to_date = $( "#to_date" ).val();
        var org_unit = $( "#id_org_unit" ).val();
        $('#data-table > tbody').html('<tr><td colspan="3">Loading data</td></tr>');

        var buttonCommon = {
            exportOptions: {
                format: {
                    body: function ( data, row, column, node ) {
                        return data;
                    }
                }
            }
        };
        console.log('proceed');

        $('#data-table').DataTable( {
            ajax:{"url": "{% url 'dq_data' %}",
                  "data": function ( d ) {
                        d.q_aspect = q_aspect;
                        d.variance = variance;
                        d.from_date = from_date;
                        d.to_date = to_date;
                        d.org_unit = org_unit;
                        d.age = age;
                 }
             },
            columns: [
                { data: 'id' },
                { data: 'case_date' },
                { data: 'cpims_id' },
                { data: 'names' },
                { data: 'dob' },
                { data: 'sex' },
                { data: 'age' },
                { data: 'case_category' },
                { data: 'org_unit' },
                { data: 'case_status' },                
                { data: 'intervention' }
            ],
            dom: 'lBfrtip',
            destroy: true,
            lengthMenu: [[10, 25, 50], [10, 25, 50]],
            buttons: [
                $.extend( true, {}, buttonCommon, {
                    extend: 'copyHtml5'
                } ),
                $.extend( true, {}, buttonCommon, {
                    extend: 'excelHtml5'
                } ),
                $.extend( true, {}, buttonCommon, {
                    extend: 'pdfHtml5',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    customize: function (doc) {
                        doc.pageMargins = [15, 30, 15, 30 ];
                        doc.content[1].table.widths = 
                            Array(doc.content[1].table.body[0].length + 1).join('*').split('');

                        doc['footer']=(function(page, pages) {
                        return {
                            columns: [
                                'Child Protection Information Management System (CPIMS)',
                                {
                                    // This is the right column
                                    alignment: 'right',
                                    text: ['Page ', { text: page.toString() },  ' of ', { text: pages.toString() }]
                                }
                            ],
                            margin: [15, 0]
                        }
                    });
                        
                      }
                } )
            ]
        } );
           return false;

    });
} );
</script>
{% endblock %}

templates/management/se_home.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %} CPIMS Staff Establishment {% endblock %}

{% load app_filters %}

{% load crispy_forms_tags %}

{% block style_code %}
<link href="{% static 'plugins/datatables/css/data-table.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/bootstrap-datepicker/css/datepicker3.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet" />
<style type="text/css">
    
table.display {
    width: 100%;
    margin: 0;
}


</style>
{% endblock %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">Staff Establishment</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header"> CPIMS Management <small> Staff Establishment</small></h1>
<!-- end page-header -->
<div id="messages" class="alert alert-danger fade in" style="display: none;" tabindex="1">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <span class="invalid-form-message" id="invalid-form-message"></span>
</div>
<!-- begin row -->
<div class="row">
  <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>                      
                <h4 class="panel-title">Staff Establishment</h4>
            </div>
            <!-- start panel body -->
            <div class="panel-body">
                <form id="dqcases" method="POST" action=".">
                    {% csrf_token %}
                    
                <div class="row">
                    
                    <div class="col-md-6">
                        <div class="form-group">
                        <label for="age">Organization Unit</label>
                        {{ form.org_unit }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                        <label for="age">County</label>
                        {{ form.county }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    
                    <div class="col-md-12">
                        <button type="button" class="btn btn-sm btn-primary m-r-5 ddash"> Filter </button>
                        <button type="reset" class="btn btn-sm btn-default"> Reset </button>
                        <span id="mng_messages">Pick None of the Organization unit or County to use ALL.</span>
                    </div>
                </div>
                </form>
                <hr>
                <div class="row">

                    <div class="col-md-12">
                        <table id="data-table" class="table table-striped table-bordered table-td-valign-middle" width="100%">
                        <thead>
                        <tr>
                        <th>CPIMS ID</th>
                        <th>Names of Officer</th>
                        <th>DOB</th>
                        <th>Sex</th>
                        <th>Age</th>
                        <th>Designation</th>
                        <th>County</th>
                        <th>Org Unit / Station</th>                        
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <!-- end panel body -->
        </div>
        <!-- end panel -->  
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->

{% endblock %}

{% block lazy_javascript_code %}
<script src="{% static 'plugins/datatables/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/select2/dist/js/select2.min.js' %}"></script>
<script src="{% static 'plugins/datatables/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/datatables/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'js/buttons.html5.min.js' %}"></script>

<script>
$(document).ready(function() {
    $('#from_date, #to_date').datepicker({
        dateFormat: 'yy-mm-dd', format: 'dd-M-yyyy',
        endDate: '+0d', enddate: '+0d', autoclose: true
    });

    $("#id_org_unit, #county").select2();


    $('.ddash').on('click', function(ev) {
        // var hashValue = location.hash.replace(/^#/, '');
        var id = $(this).attr('id');
        var org_unit = $( "#id_org_unit" ).val();
        var county = $( "#county" ).val();
        $('#data-table > tbody').html('<tr><td colspan="3">Loading data</td></tr>');

        var buttonCommon = {
            exportOptions: {
                format: {
                    body: function ( data, row, column, node ) {
                        return data;
                    }
                }
            }
        };
        console.log('proceed');

        $('#data-table').DataTable( {
            ajax:{"url": "{% url 'se_data' %}",
                  "data": function ( d ) {
                        d.org_unit = org_unit;
                        d.county = county;
                 }
             },
            columns: [
                { data: 'cpims_id' },
                { data: 'names' },
                { data: 'dob' },
                { data: 'sex' },
                { data: 'age' },
                { data: 'designation' },                
                { data: 'county' },
                { data: 'org_unit' }
            ],
            dom: 'Bfrtip',
            destroy: true,
            buttons: [
                $.extend( true, {}, buttonCommon, {
                    extend: 'copyHtml5'
                } ),
                $.extend( true, {}, buttonCommon, {
                    extend: 'excelHtml5'
                } ),
                $.extend( true, {}, buttonCommon, {
                    extend: 'pdfHtml5',
                    orientation: 'landscape',
                    watermark: { text: 'test watermark', angle: 70 },
                    exportOptions: {
                        columns: ':visible'
                    },
                    customize: function (doc) {
                        doc.pageMargins = [15, 30, 15, 30 ];
                        doc.content[1].table.widths = 
                            Array(doc.content[1].table.body[0].length + 1).join('*').split('');

                        doc['footer']=(function(page, pages) {
                        return {
                            columns: [
                                'Child Protection Information Management System (CPIMS)',
                                {
                                    // This is the right column
                                    alignment: 'right',
                                    text: ['Page ', { text: page.toString() },  ' of ', { text: pages.toString() }]
                                }
                            ],
                            margin: [15, 0]
                        }
                    });
                        
                      }
                } )
            ]
        } );
           return false;

    });
} );
</script>
{% endblock %}