cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from . import views
import cpovc_auth
import cpovc_access
from django.urls import include, path, re_path
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_registry import views as registry_views

from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_ovc import urls as ovc_urls
from cpovc_settings import urls as settings_urls
from cpovc_manage import urls as manage_urls
from cpovc_help import urls as help_urls
from notifications import urls as noti_urls
from cpovc_ctip import urls as ctip_urls
from cpovc_afc import urls as ac_urls

from django.views.generic import TemplateView
# For dashboard
from cpovc_dashboard import urls as dashboard_api_urls
from cpovc_dashboard import views as dash_views


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$', 'cpovc_auth.views.log_in', name='home'),
    path('', views.home, name='home'),
    path('accounts/request/', views.access, name='access'),
    path('accounts/terms/<int:id>/', cpovc_access.views.terms,
         name='terms'),
    path('register/', cpovc_auth.views.register, name='register'),
    path('auth/', include(auth_urls)),
    path('registry/', include(registry_urls)),
    path('forms/', include(forms_urls)),
    path('reports/', include(reports_urls)),
    path('gis/', include(gis_urls)),
    path('api/v1/', include(api_urls)),
    path('ovc_care/', include(ovc_urls)),
    path('settings/', include(settings_urls)),
    path('manage/', include(manage_urls)),
    path('help/', include(help_urls)),
    path('forms/ctip/', include(ctip_urls)),
    path('forms/altcare/', include(ac_urls)),
    path('notifications/', include(noti_urls, namespace='notifications')),
    re_path(r'^dashboard/(?P<did>[A-Z{2}]+)/$',
            registry_views.dashboard, name='dashboard'),
    # Accounts management
    path('accounts/', include(cpovc_auth.urls)),
    # Override Login and Logout not to use the /accounts/*
    path('login/', cpovc_auth.views.log_in, name='login'),
    path('logout/', cpovc_auth.views.log_out, name='logout'),
    path('d/', dash_views.ovc_dashboard, name='ovc_dashboard'),
    re_path(r'^api/v2/', include(dashboard_api_urls)),
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                                   content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

cpovc_afc/urls.py
from django.urls import path, re_path
from . import views

# This should contain urls related to Care reforms ONLY
urlpatterns = [
    path('', views.alt_care_home, name='alternative_care'),
    path(
        'new/<uuid:case_id>/', views.new_alternative_care,
        name='new_alt_care'),
    path(
        'view/<uuid:care_id>/', views.view_alternative_care,
        name='view_alt_care'),
    path(
        'edit/<uuid:care_id>/', views.edit_alternative_care,
        name='edit_alt_care'),
    re_path(r'^(?P<cid>[A-Z{2}]+)/(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<care_id>[0-9A-Za-z_\-{32}]+)/$',
            views.alt_care_form, name='alt_care_form'),
    re_path(r'^(?P<cid>[A-Z{2}]+)/(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<care_id>[0-9A-Za-z_\-{32}]+)/(?P<ev_id>\d+)/$',
            views.edit_alt_care_form, name='edit_alt_care_form'),
    re_path(r'^(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<event_id>[0-9A-Za-z_\-{32}]+)/$',
            views.delete_alt_care_form, name='delete_alt_care_form'),
]

cpovc_ctip/urls.py
from django.urls import path, re_path
from . import views

# This should contain urls related to CTiP ONLY
urlpatterns = [
    path('', views.ctip_home, name='ctip_home'),
    re_path(r'^case/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$', views.view_ctip_case, name='view_ctip_case'),
    re_path(r'^form/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/(?P<id>\d+)/$',
            views.ctip_forms, name='ctip_forms'),
    re_path(r'^form/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$',
            views.ctip_form, name='ctip_form'),
    re_path(r'^form/view/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$',
            views.view_ctip_form, name='view_ctip_form'),
    path('new/<uuid:case_id>/', views.new_ctip_case, name='new_ctip_case'),
    path('edit/<uuid:case_id>/', views.edit_ctip_case, name='edit_ctip_case'),
]

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion
# pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.notifications_home, name='home'),
    pattern(r'^(?P<id>\d+)/$', views.notifications_read, name='read'),
    pattern(r'^all/$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

templates/base_home.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<title>CPIMS | {% block page_title %}{% endblock %}</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
        <meta name="robots" content="noindex">
	<meta name="theme-color" content="#89CFF0" />
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<link href="{% static 'plugins/jquery-ui/themes/base/minified/jquery-ui.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/style.css' %}" rel="stylesheet" />
	<link href="{% static 'css/style-responsive.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/theme/default.css' %}" rel="stylesheet" id="theme" />
	<!-- ================== END BASE CSS STYLE ================== -->
	{% block style_code %}
    <link href="{% static 'plugins/parsley/src/parsley.css' %}" rel="stylesheet" />
    <style type="text/css">
    	 /* Three image containers (use 25% for four, and 50% for two, etc) */
		.column {
		  float: left;
		  width: 35%;
		  padding: 5px;
		  margin-right: 10px;
		}
		.column-l {
		  float: left;
		  width: 10%;
		  padding: 5px;
		}

		/* Clear floats after image containers */
		.branding::after {
		  content: "";
		  clear: both;
		  display: table;
		} 
    </style>
	{% endblock style_code %}
    {% block extra_styling %}{% endblock extra_styling %}
	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static 'plugins/pace/pace.min.js' %}"></script>
    {% block javascript_code %}{% endblock %}
	<!-- ================== END BASE JS ================== -->
</head>
<body class="pace-top bg-white">
	<!-- begin #page-loader -->
	<div id="page-loader" class="fade in"><span class="spinner"></span></div>
	<!-- end #page-loader -->
	
	<!-- begin #page-container -->
	<div id="page-container" class="fade">
	    <!-- begin register -->
        <div class="register register-with-news-feed">
            <!-- begin news-feed -->
            <div class="news-feed">
                <div class="news-image">
                    <img src="{% static 'img/dcs.jpg' %}" alt="" height="100%" />
                </div>
                <div class="news-caption">
                    <h4 class="caption-title"><img src="{% static 'img/logo_gok.png' %}" height="80"> Child Protection Information Management System</h4>
                    <p>The National Council for Children's Services (NCCS) and the Directorate of Children Services (DCS) are charged with implementing and enforcing the provisions of Section 53 of the Constitution of Kenya and the Children Act, 2022. Section 38(c) - The Secretary shall maintain up-to-date records and data on management of children services including access to welfare amenities for children.</p>
                </div>
            </div>
            <!-- end news-feed -->
            {% block primary %} {% endblock primary %}
        </div>
        <!-- end register -->
        
	</div>
	<!-- end page container -->
	
	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static 'plugins/jquery/jquery-1.9.1.min.js' %}"></script>
	<script src="{% static 'plugins/jquery/jquery-migrate-1.1.0.min.js' %}"></script>
	<script src="{% static 'plugins/jquery-ui/ui/minified/jquery-ui.min.js' %}"></script>
	<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
	<!--[if lt IE 9]>
		<script src="{% static 'crossbrowserjs/html5shiv.js' %}"></script>
		<script src="{% static 'crossbrowserjs/respond.min.js' %}"></script>
		<script src="{% static 'crossbrowserjs/excanvas.min.js' %}"></script>
	<![endif]-->
	<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'plugins/jquery-cookie/jquery.cookie.js' %}"></script>
    <script src="{% static 'plugins/parsley/dist/parsley.js' %}"></script>
	<!-- ================== END BASE JS ================== -->
	
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'js/apps.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->
    {% block lazy_javascript_code %}{% endblock lazy_javascript_code %}
	<script>
        jQuery(document).ready(function() {
			App.init();
            $("#id_email").addClass( "form-control input-lg" );
            $('#id_email').attr('data-parsley-required', 'true');
		});
	</script>
</body>
</html>

templates/blank.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %} OVC Care Home {% endblock %}

{% load crispy_forms_tags %}

{% block style_code %}

{% endblock %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">OVC Care</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header"><i class="fa fa-child"></i> OVC Care <small>Home</small></h1>
<!-- end page-header -->
<div id="messages" class="alert alert-danger fade in" style="display: none;" tabindex="1">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <span class="invalid-form-message" id="invalid-form-message"></span>
</div>
<!-- begin row -->
<div class="row">
  <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>                      
                <h4 class="panel-title">Heading &nbsp;<i class="fa fa-male"></i></h4>
            </div>
            <!-- start panel body -->
            <div class="panel-body">
            </div>
            <!-- end panel body -->
        </div>
        <!-- end panel -->  
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->
{% endblock %}

{% block lazy_javascript_code %}

{% endblock %}

templates/csrf.html
{% extends 'base_home.html' %}
{% load static %}

{% block page_title %} {{block.super}} CSRF error {% endblock page_title%}    

{% block primary %}
<!-- begin right-content -->
<div class="right-content">
    <!-- begin register-header -->
    <div class="register-header">
        <h4 class="brand shome">Department of Children Services (DCS)</h4>
    </div>
    <h1 class="register-header">
        <small>There was a server error while processing your request </small>
    </h1>
    <!-- end register-header -->  
    <!-- begin register-content -->
    <div class="register-content"> 

        <div class="m-t-40 m-b-40">
        	<p>{{ reason }}</p>
            <p><strong>Cross-Site Request Forgery (CSRF) error may occur because of:</strong></p>
			<ol type="a">
			<li>Using the <strong>back button</strong></li>
			<li>An actual <strong>attack on your browser requests to the server</strong></li>
			<li>A <strong>other reason</strong></li>
			</ol>
		</div>
		<div class="m-t-20 m-b-20 p-b-20">
	        Please visit our <a href="{% url 'home' %}" class="text-success">home page</a> or 
	        <a href="{% url 'login' %}" class="text-success">login page</a> to start a fresh or contact administrator at cpims&lt;@&gt;labour&lt;dot&gt;go.ke
	    </div>
	        <span class="promo m-t-40">
	            <p>
	                <img src="{% static 'img/logo_public.jpg' %}" height="80">
	            </span>
	            <hr />
	            <p class="text-center text-inverse">
	                &copy; {% now "Y" %} Department of Children Services (DCS). All Rights Reserved.
	            </p>
    </div>
    <!-- end register-content -->
</div>
<!-- end right-content -->
{% endblock primary %}

templates/guests.html
<!-- begin breadcrumb -->
{% load static %}
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">{{ request.get_full_path }}</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">CPIMS <small>Coming soon page</small></h1>
<!-- end page-header -->

<div class="row">
    <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <h4 class="panel-title">Guest details</h4>
            </div>
            <div class="panel-body">
                <img align="center" src="{% static 'img/under_construction.png' %}">
            </div>
        </div>
    </div>
</div>
<!-- end row -->

templates/index.html
<html>
<head>
<title>CPIMS - Dashboard</title>
</head>
<body>
<p>CPIMS details page</p>
</body>
</html>

templates/locked.html
{% extends 'base_home.html' %}
{% load static %}

{% block page_title %} {{block.super}} Locked out {% endblock page_title%}    

{% block primary %}
<!-- begin right-content -->
<div class="right-content">
    <!-- begin login-header -->
    <div class="register-header">
        <h4 class="brand">Department of Children Services (DCS)</h4>
        <hr />
    </div>
    <!-- begin register-header -->
    <h1 class="register-header">
        <small>Account locked</small>
    </h1>
    <!-- end register-header -->
    
    <!-- begin register-content -->
    <div class="register-content">
        {% if messages %}
            {% for message in messages %}
            {% if 'error' in message.tags %}
                <div id="messages" class="alert alert-danger fade in m-b-15">
                <span class="close" data-dismiss="alert">×</span>
                <i class="fa fa-info fa-2x pull-left"></i>
            {% else %}
                <div id="messages" class="alert alert-success fade in">
                <span class="close" data-dismiss="alert">×</span>
                <i class="fa fa-check fa-2x pull-left"></i>
            {% endif %}    
                <p>{{ message }}</p>
            </div>
           {% endfor %}
        {% endif %}
        <div class="alert alert-danger fade in">
            <span class="close" data-dismiss="alert">×</span>
            <i class="fa fa-check fa-2x pull-left"></i>
            <p>Too many failed login attempts for this account. <br/>Please contact the administrator or try again later after 15 minutes.</p>
        </div>
        <div class="checkbox m-b-30">
            <p>
                Please read and agree to our <a href="{% url 'terms' id=1 %}">Terms</a> and our <a href="{% url 'terms' id=2 %}">Data Policy</a>, including our <a href="{% url 'terms' id=3 %}">Cookie Use</a>.
            </p>
        </div>
        <div class="m-t-10 m-b-10 p-b-10">
            Already a registered user? Click <a href="{% url 'login' %}">here</a> to login.<br/>
            Not registered yet? Click <a href="{% url 'access' %}" class="text-success">here</a> to request for access.
        </div>
            <span class="promo">
                <p>
                 <div class="row branding">
                  <div class="column">
                    <img src="{% static 'img/UNICEF-logo.png' %}" height="40" alt="UNICEF" >
                  </div>
                  <div class="column">
                    <img src="{% static 'img/USAID-logo.png' %}" height="40" alt="USAID" >
                  </div>
                  <div class="column-l">
                    <img src="{% static 'img/PEPFAR-logo.png' %}" height="60" alt="PEPFAR" >
                  </div>
                </div>
                </p>
                </span>
                <hr />
            <p class="text-center text-inverse">
                &copy; {% now "Y" %} Department of Children Services (DCS). All Rights Reserved.
            </p>
        </form>
    </div>
    <!-- end register-content -->
</div>
<!-- end right-content -->
{% endblock primary %}

{% block lazy_javascript_code %}{% endblock lazy_javascript_code %}

templates/menus.html
{% load app_class %}
{% load notifications_tags %}
<ul class="nav">
	<li class="nav-header">Navigation</li>
	<li class="has-sub {{ request.path|get_class:'/' }} {{ request.path|get_class:'dashboard' }}">
		<a href="{% url 'home' %}">
		    <i class="fa fa-laptop"></i>
		    <span>Home</span>
	    </a>
	</li>
	
	<li class="has-sub {{ request.path|get_class:'registry' }}">
		<a href="#">
		    <b class="caret pull-right"></b>
		    <i class="fa fa-suitcase"></i>
		    <span>Registry</span> 
		</a>
		<ul class="sub-menu">
			<li><a href="{% url 'registry' %}">Organizational Units</a></li>
			<li><a href="{% url 'search_persons' %}">Persons Registry</a></li>
		</ul>
	</li>
	
	<li class="has-sub {{ request.path|get_class:'forms' }} {{ request.path|get_class:'ovcare' }}">
		<a href="#">
		    <b class="caret pull-right"></b>
		    <i class="fa fa-file-o"></i>
		    <span>Forms</span>
		</a>
	    <ul class="sub-menu">
			<li><a href="{% url 'case_record_sheet' %}">Case Record Sheet</a></li>
			<li><a href="{% url 'residential_placement' %}">Institutional Placement</a></li>
			<li><a href="{% url 'alternative_family_care' %}">Alternative Family Care</a></li>
			<li><a href="{% url 'alternative_care' %}">Alternative Care</a></li>
			<li><a href="{% url 'background_details' %}">School and Bursary</a></li>
			<li><a href="{% url 'forms_registry' %}">Follow-ups</a></li>
			<li><a href="{% url 'documents_manager' %}">Documents Manager</a></li>
			<li><a href="{% url 'ovc_home' %}">OVC Care</a></li>
			<li><a href="#">Family Support / HES</a></li>
			<li><a href="{% url 'ctip_home' %}">Trafficked Persons</a></li>
		</ul>
		
	</li>
			
	
	<li class="has-sub {{ request.path|get_class:'reports' }}">
	    <a href="#">
		    <b class="caret pull-right"></b>
	        <i class="fa fa-area-chart"></i>
		    <span>Reports</span>
		</a>
		<ul class="sub-menu">
		    <li><a href="{% url 'caseload_reports' %}">Case Load Report</a></li>
		    <li><a href="{% url 'cpims_reports' id=1 %}">KNBS Report</a></li>
		    <li><a href="{% url 'cpims_reports' id=3 %}">Institutions Population Returns Report </a></li>
		    <li><a href="{% url 'cpims_reports' id=4 %}">Health Report </a></li>
		    <li><a href="{% url 'cpims_reports' id=5 %}">Ad Hoc Report </a></li>
		    <li><a href="{% url 'pivot_reports' %}">Ad Hoc Pivot Report </a></li>
		    <li><a href="{% url 'document_reports' %}">Document Templates </a></li>
		    <li class="has-sub">
				<a href="#">
				    <b class="caret pull-right"></b>
				    <i class="fa fa-align-left"></i> 
				    <span>Alternative Care Reports</span>
				</a>
				<ul class="sub-menu">
					<li><a href="{% url 'reports_afc' id=1 %}">AFC Summpary report</a></li>
					<li><a href="{% url 'reports_afc' id=2 %}">Identification Report</a></li>
					<li><a href="{% url 'reports_afc' id=3 %}">Assessment Report - Child</a></li>
					<li><a href="{% url 'reports_afc' id=4 %}">Assessment Report - Family</a></li>
					<li><a href="{% url 'reports_afc' id=5 %}">Case Plan</a></li>
					<li><a href="{% url 'reports_afc' id=6 %}">Placement Report</a></li>
					<li><a href="{% url 'reports_afc' id=7 %}">Monitoring</a></li>
					<li><a href="{% url 'reports_afc' id=8 %}">Case Review - Child</a></li>
					<li><a href="{% url 'reports_afc' id=9 %}">Case Review - Caregiver</a></li>
				</ul>
			</li>
		    <li class="has-sub">
				<a href="#">
				    <b class="caret pull-right"></b>
				    <i class="fa fa-align-left"></i> 
				    <span>OVC Reports</span>
				</a>
				<ul class="sub-menu">
					<li><a href="{% url 'pivot_ovc_reports' %}">DATIM</a></li>
					<li><a href="{% url 'pivot_ovc_pepfar' %}">Services by Domain (PEPFAR Summary)</a></li>
					<li><a href="{% url 'pivot_ovc_kpi' %}">Key Performance Indicator</a></li>
					<li><a href="{% url 'reports_ovc' id=1 %}">Registration List</a></li>
					<li><a href="{% url 'reports_ovc' id=2 %}">Registration by HH</a></li>
					<li><a href="{% url 'reports_ovc' id=3 %}">CSI</a></li>
					<li><a href="{% url 'reports_ovc' id=4 %}">CHV monthly RR</a></li>
					<li><a href="{% url 'reports_ovc' id=5 %}">List of OVC not served</a></li>
                                        <li><a href="{% url 'reports_ovc' id=12 %}">List of OVC Served</a></li>
					<li><a href="{% url 'reports_ovc' id=6 %}">PEPFAR detailed summary</a></li>
					<li><a href="{% url 'reports_ovc' id=7 %}">Registration by CHV</a></li>
					<li><a href="{% url 'reports_ovc' id=8 %}">Beneficiary list</a></li>
					<li><a href="{% url 'reports_ovc' id=9 %}">Form1a summary</a></li>
					<li><a href="{% url 'reports_ovc' id=10 %}">Needs vs Served by domain</a></li>
				</ul>
			</li>
		</ul>
	</li>

	<li class="has-sub {{ request.path|get_class:'manage' }} {{ request.path|get_class:'settings' }}">
	    <a href="#">
	        <b class="caret pull-right"></b>
	        <i class="fa fa-tasks"></i>
	        <span>Management</span>
	    </a>
		<ul class="sub-menu">
			<li><a href="{% url 'home_travel' %}" >Non Objection to Travel</a></li>
			<li><a href="{% url 'integration_home' %}" >API Integration</a></li>
			<li><a href="{% url 'dq_home' %}" >Data Quality</a></li>
			<li><a href="{% url 'se_home' %}" >Staff Establishment</a></li>
            <li><a href="{% url 'settings_duplicates' %}" >De-duplication</a></li>
            <li><a href="{% url 'settings_reports' %}" >Archived Reports</a></li>
		</ul>
	</li>
	
	<li class="has-sub {{ request.path|get_class:'gis' }}">
	    <a href="#">
	        <b class="caret pull-right"></b>
	        <i class="fa fa-map-marker"></i>
	        <span>GIS Module</span>
	    </a>
		<ul class="sub-menu">
			<li><a href="{% url 'gis_home' %}" >Map</a></li>
		</ul>
	</li>
	<li class="has-sub">
	    <a href="#">
		    <b class="caret pull-right"></b>
		    <i class="fa fa-camera"></i>
		    <span>Gallery</span>
		</a>
	    <ul class="sub-menu">
	        <li><a href="#">Gallery One</a></li>
	        <li><a href="#">Gallery Two</a></li>
	    </ul>
	</li>			
	
	<li class="has-sub">
	    <a href="#">
		    <b class="caret pull-right"></b>
		    <i class="fa fa-question"></i>
		    <span>Help and Documents</span>
		</a>
	    <ul class="sub-menu">
	        <li><a href="{% url 'help_downloads' %}">Downloads</a></li>
	        <li><a href="{% url 'help_faq' %}">FAQ</a></li>
	    </ul>
	</li>
	<li>
		<a href="{% url 'notifications:home' %}">
			<span class="badge pull-right">{% live_notify_badge %}</span>
			<i class="fa fa-inbox"></i> 
			<span>Notifications</span>
		</a>
	</li>
    <!-- begin sidebar minify button -->
	<li><a href="#" class="sidebar-minify-btn" data-click="sidebar-minify">
	    <i class="fa fa-angle-double-left"></i></a>
	</li>
    <!-- end sidebar minify button -->
    <li><a href="https://play.google.com/store/apps/details?id=com.poimapper.vurugumapper">
    	<i class="fa fa-download"></i> <span>Vurugu Mapper(Android)</span></a>
    </li>
    <li><img width="220px" src="/static/img/qr-vm.png">
    </li>
</ul>