cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from . import views
import cpovc_auth
import cpovc_access
from django.urls import include, path, re_path
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_registry import views as registry_views

from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_ovc import urls as ovc_urls
from cpovc_settings import urls as settings_urls
from cpovc_manage import urls as manage_urls
from cpovc_help import urls as help_urls
from notifications import urls as noti_urls
from cpovc_ctip import urls as ctip_urls
from cpovc_afc import urls as ac_urls

from django.views.generic import TemplateView
# For dashboard
from cpovc_dashboard import urls as dashboard_api_urls
from cpovc_dashboard import views as dash_views


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$', 'cpovc_auth.views.log_in', name='home'),
    path('', views.home, name='home'),
    path('accounts/request/', views.access, name='access'),
    path('accounts/terms/<int:id>/', cpovc_access.views.terms,
         name='terms'),
    path('register/', cpovc_auth.views.register, name='register'),
    path('auth/', include(auth_urls)),
    path('registry/', include(registry_urls)),
    path('forms/', include(forms_urls)),
    path('reports/', include(reports_urls)),
    path('gis/', include(gis_urls)),
    path('api/v1/', include(api_urls)),
    path('ovc_care/', include(ovc_urls)),
    path('settings/', include(settings_urls)),
    path('manage/', include(manage_urls)),
    path('help/', include(help_urls)),
    path('forms/ctip/', include(ctip_urls)),
    path('forms/altcare/', include(ac_urls)),
    path('notifications/', include(noti_urls, namespace='notifications')),
    re_path(r'^dashboard/(?P<did>[A-Z{2}]+)/$',
            registry_views.dashboard, name='dashboard'),
    # Accounts management
    path('accounts/', include(cpovc_auth.urls)),
    # Override Login and Logout not to use the /accounts/*
    path('login/', cpovc_auth.views.log_in, name='login'),
    path('logout/', cpovc_auth.views.log_out, name='logout'),
    path('d/', dash_views.ovc_dashboard, name='ovc_dashboard'),
    re_path(r'^api/v2/', include(dashboard_api_urls)),
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                                   content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

cpovc_afc/urls.py
from django.urls import path, re_path
from . import views

# This should contain urls related to Care reforms ONLY
urlpatterns = [
    path('', views.alt_care_home, name='alternative_care'),
    path(
        'new/<uuid:case_id>/', views.new_alternative_care,
        name='new_alt_care'),
    path(
        'view/<uuid:care_id>/', views.view_alternative_care,
        name='view_alt_care'),
    path(
        'edit/<uuid:care_id>/', views.edit_alternative_care,
        name='edit_alt_care'),
    re_path(r'^(?P<cid>[A-Z{2}]+)/(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<care_id>[0-9A-Za-z_\-{32}]+)/$',
            views.alt_care_form, name='alt_care_form'),
    re_path(r'^(?P<cid>[A-Z{2}]+)/(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<care_id>[0-9A-Za-z_\-{32}]+)/(?P<ev_id>\d+)/$',
            views.edit_alt_care_form, name='edit_alt_care_form'),
    re_path(r'^(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<event_id>[0-9A-Za-z_\-{32}]+)/$',
            views.delete_alt_care_form, name='delete_alt_care_form'),
]

cpovc_ctip/urls.py
from django.urls import path, re_path
from . import views

# This should contain urls related to CTiP ONLY
urlpatterns = [
    path('', views.ctip_home, name='ctip_home'),
    re_path(r'^case/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$', views.view_ctip_case, name='view_ctip_case'),
    re_path(r'^form/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/(?P<id>\d+)/$',
            views.ctip_forms, name='ctip_forms'),
    re_path(r'^form/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$',
            views.ctip_form, name='ctip_form'),
    re_path(r'^form/view/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$',
            views.view_ctip_form, name='view_ctip_form'),
    path('new/<uuid:case_id>/', views.new_ctip_case, name='new_ctip_case'),
    path('edit/<uuid:case_id>/', views.edit_ctip_case, name='edit_ctip_case'),
]

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion
# pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.notifications_home, name='home'),
    pattern(r'^(?P<id>\d+)/$', views.notifications_read, name='read'),
    pattern(r'^all/$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

notifications/views.py
# -*- coding: utf-8 -*-
''' Django Notifications exemple views '''
from distutils.version import StrictVersion
# pylint: disable=no-name-in-module,import-error
from django.shortcuts import render
from django import get_version
from django.contrib.auth.decorators import login_required
from django.forms import model_to_dict
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from notifications import settings
from notifications.models import Notification
from notifications.utils import id2slug, slug2id
from notifications.settings import get_config

if StrictVersion(get_version()) >= StrictVersion('1.7.0'):
    from django.http import JsonResponse  # noqa
else:
    # Django 1.6 doesn't have a proper JsonResponse
    import json
    from django.http import HttpResponse  # noqa

    def date_handler(obj):
        return obj.isoformat() if hasattr(obj, 'isoformat') else obj

    def JsonResponse(data):  # noqa
        return HttpResponse(
            json.dumps(data, default=date_handler),
            content_type="application/json")


class NotificationViewList(ListView):
    template_name = 'notifications/list.html'
    context_object_name = 'notifications'
    paginate_by = settings.get_config()['PAGINATE_BY']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(NotificationViewList, self).dispatch(
            request, *args, **kwargs)


class AllNotificationsList(NotificationViewList):
    """
    Index page for authenticated user
    """

    def get_queryset(self):
        if settings.get_config()['SOFT_DELETE']:
            qset = self.request.user.notifications.active()
        else:
            qset = self.request.user.notifications.all()
        return qset


class UnreadNotificationsList(NotificationViewList):

    def get_queryset(self):
        return self.request.user.notifications.unread()


@login_required
def mark_all_as_read(request):
    request.user.notifications.mark_all_as_read()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)
    return redirect('notifications:home')


@login_required
def mark_as_read(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)
    notification.mark_as_read()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:home')


@login_required
def mark_as_unread(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)
    notification.mark_as_unread()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def delete(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)

    if settings.get_config()['SOFT_DELETE']:
        notification.deleted = True
        notification.save()
    else:
        notification.delete()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:all')


def live_unread_notification_count(request):
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'unread_count': 0
        }
    else:
        data = {
            'unread_count': request.user.notifications.unread().count(),
        }
    return JsonResponse(data)


def live_unread_notification_list(request):
    ''' Return a json with a unread notification list '''
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'unread_count': 0,
            'unread_list': []
        }
        return JsonResponse(data)

    default_num_to_fetch = get_config()['NUM_TO_FETCH']
    try:
        # If they don't specify, make it 5.
        num_to_fetch = request.GET.get('max', default_num_to_fetch)
        num_to_fetch = int(num_to_fetch)
        if not (1 <= num_to_fetch <= 100):
            num_to_fetch = default_num_to_fetch
    except ValueError:  # If casting to an int fails.
        num_to_fetch = default_num_to_fetch

    unread_list = []

    for notification in request.user.notifications.unread()[0:num_to_fetch]:
        struct = model_to_dict(notification)
        struct['slug'] = id2slug(notification.id)
        if notification.actor:
            struct['actor'] = str(notification.actor)
        if notification.target:
            struct['target'] = str(notification.target)
        if notification.action_object:
            struct['action_object'] = str(notification.action_object)
        if notification.data:
            struct['data'] = notification.data
        if notification.timesince:
            struct['timesince'] = str(notification.timesince().encode('utf-8'))
        unread_list.append(struct)
        if request.GET.get('mark_as_read'):
            notification.mark_as_read()
    data = {
        'unread_count': request.user.notifications.unread().count(),
        'unread_list': unread_list
    }
    return JsonResponse(data)


def live_all_notification_list(request):
    ''' Return a json with a unread notification list '''
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'all_count': 0,
            'all_list': []
        }
        return JsonResponse(data)

    default_num_to_fetch = get_config()['NUM_TO_FETCH']
    try:
        # If they don't specify, make it 5.
        num_to_fetch = request.GET.get('max', default_num_to_fetch)
        num_to_fetch = int(num_to_fetch)
        if not (1 <= num_to_fetch <= 100):
            num_to_fetch = default_num_to_fetch
    except ValueError:  # If casting to an int fails.
        num_to_fetch = default_num_to_fetch

    all_list = []

    for notification in request.user.notifications.all()[0:num_to_fetch]:
        struct = model_to_dict(notification)
        struct['slug'] = id2slug(notification.id)
        if notification.actor:
            struct['actor'] = str(notification.actor)
        if notification.target:
            struct['target'] = str(notification.target)
        if notification.action_object:
            struct['action_object'] = str(notification.action_object)
        if notification.data:
            struct['data'] = notification.data
        if notification.timesince:
            struct['timesince'] = str(notification.timesince().encode('utf-8'))
        all_list.append(struct)
        if request.GET.get('mark_as_read'):
            notification.mark_as_read()
    data = {
        'all_count': request.user.notifications.count(),
        'all_list': all_list
    }
    return JsonResponse(data)


def live_all_notification_count(request):
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'all_count': 0
        }
    else:
        data = {
            'all_count': request.user.notifications.count(),
        }
    return JsonResponse(data)


@login_required
def notifications_home(request):
    """Method to do pivot reports."""
    try:
        return render(request, 'notifications/home.html', {'form': {}})
    except Exception as e:
        raise e
    else:
        pass


@login_required
def notifications_read(request, id):
    """Method to do pivot reports."""
    try:
        notification = get_object_or_404(
            Notification, recipient=request.user, id=id)
        return render(request, 'notifications/details.html',
                      {'form': {}, 'notification': notification})
    except Exception as e:
        raise e
    else:
        pass

notifications/templates/notifications/blank.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %} Notifications {% endblock %}

{% load crispy_forms_tags %}

{% block style_code %}

{% endblock %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">Notifications</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">System Notifications <small>Home</small></h1>
<!-- end page-header -->
<div id="messages" class="alert alert-danger fade in" style="display: none;" tabindex="1">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <span class="invalid-form-message" id="invalid-form-message"></span>
</div>
<!-- begin row -->
<div class="row">
  <!-- begin vertical-box -->
        <div class="vertical-box">
            <{% for notice in notifications %}
			    {% include 'notifications/message.html' %}
			{% endfor %}
        </div>
        <!-- end vertical-box -->
</div>
<!-- end row -->
{% endblock %}

{% block lazy_javascript_code %}
<script type="text/javascript">
    
    $.get( "{% url 'notifications:live_all_notification_count' %}", function( data ) {
      $( ".total_msgs" ).html( data.all_count + " message(s)" );
      $( ".all_msgs" ).html( data.all_count );
    });

    
    $.get( "{% url 'notifications:mark_as_read' slug=notification.slug %}", function( data ) {});

</script>

{% endblock %}

notifications/templates/notifications/details.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %} Notifications {% endblock %}

{% load crispy_forms_tags %}

{% block style_code %}

{% endblock %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">Notifications</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">System Notifications <small>Home</small></h1>
<!-- end page-header -->
<div id="messages" class="alert alert-danger fade in" style="display: none;" tabindex="1">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <span class="invalid-form-message" id="invalid-form-message"></span>
</div>
<!-- begin row -->
<div class="row">
  <!-- begin vertical-box -->
            <div class="vertical-box">
                <!-- begin vertical-box-column -->
                <div class="vertical-box-column width-250">
                    <!-- begin wrapper -->
                    <div class="wrapper bg-silver text-center">
                        <a href="#" class="btn btn-success p-l-40 p-r-40 btn-sm">
                            Compose
                        </a>
                    </div>
                    <!-- end wrapper -->
                    <!-- begin wrapper -->
                    <div class="wrapper">
                        <p><b>FOLDERS</b></p>
                        <ul class="nav nav-pills nav-stacked nav-sm">
                            <li class="active"><a href="{% url 'notifications:home' %}"><i class="fa fa-inbox fa-fw m-r-5"></i> Inbox <span class="badge pull-right all_msgs">0</span></a></li>
                            <li><a href="#"><i class="fa fa-flag fa-fw m-r-5"></i> Important</a></li>
                            <li><a href="#"><i class="fa fa-send fa-fw m-r-5"></i> Sent</a></li>
                            <li><a href="#"><i class="fa fa-pencil fa-fw m-r-5"></i> Drafts</a></li>
                            <li><a href="#"><i class="fa fa-trash fa-fw m-r-5"></i> Trash</a></li>
                        </ul>
                        <p><b>LABEL</b></p>
                        <ul class="nav nav-pills nav-stacked nav-sm m-b-0">
                            <li><a href="#"><i class="fa fa-fw m-r-5 fa-circle text-danger"></i> High Risk</a></li>
                            <li><a href="#"><i class="fa fa-fw m-r-5 fa-circle text-primary"></i> Medium Risk</a></li>
                            <li><a href="#"><i class="fa fa-fw m-r-5 fa-circle text-success"></i> Low Risk</a></li>
                            <li><a href="#"><i class="fa fa-fw m-r-5 fa-circle text-inverse"></i> System</a></li>                            
                            <li><a href="#"><i class="fa fa-fw m-r-5 fa-circle text-warning"></i> Other</a></li>
                        </ul>
                    </div>
                    <!-- end wrapper -->
                </div>
                <!-- end vertical-box-column -->
                <!-- begin vertical-box-column -->
                 <!-- begin vertical-box-column -->
                <div class="vertical-box-column bg-white">
                    <!-- begin wrapper -->
                    <div class="wrapper bg-silver-lighter clearfix">
                        <div class="btn-group m-r-5">
                            <a href="{% url 'notifications:home' %}" class="btn btn-white btn-sm"><i class="fa fa-reply"></i></a>
                        </div>
                        <div class="btn-group m-r-5">
                            <a href="#" class="btn btn-white btn-sm p-l-20 p-r-20"><i class="fa fa-trash"></i></a>
                            <a href="#" class="btn btn-white btn-sm p-l-20 p-r-20"><i class="fa fa-file"></i></a>
                        </div>
                        <div class="pull-right">
                            <div class="btn-group btn-toolbar">
                                <a href="{% url 'notifications:home' %}" class="btn btn-white btn-sm disabled"><i class="fa fa-arrow-up"></i></a>
                                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-arrow-down"></i></a>
                            </div>
                            <div class="btn-group m-l-5">
                                <a href="#" class="btn btn-white btn-sm"><i class="fa fa-times"></i></a>
                            </div>
                        </div>
                    </div>
                    <!-- end wrapper -->
                    <!-- begin wrapper -->
                    <div class="wrapper">
                        <h4 class="m-b-15 m-t-0 p-b-10 underline">{{ notification.verb }}</h4>
                        <ul class="media-list underline m-b-20 p-b-15">
                            <li class="media media-sm clearfix">
                                <a href="javascript:;" class="pull-left">
                                    <img class="media-object rounded-corner" alt="" src="{% static 'img/user-2.jpg' %}" />
                                </a>
                                <div class="media-body">
                                    <span class="email-from text-inverse f-w-600">
                                        from &lt;CPIMS&gt;
                                        
                                    </span><span class="text-muted m-l-5"><i class="fa fa-clock-o fa-fw"></i> {{ notification.timestamp }} ({{ notification.timesince }} ago)</span><br />
                                    <span class="email-to">
                                        To: {{ notification.actor }}
                                    </span>
                                </div>
                            </li>
                        </ul>
                        
                        <p class="f-s-12 text-inverse">{{ notification.description|safe }}</p>
                        <br />
                        <br />
                        <p class="f-s-12 text-inverse">
                            Best Regards,<br />
                            Admin<br /><br />
                            Child Protection Information Management System (CPIMS)<br />
                        </p>
                    </div>
                    <!-- end wrapper -->
                    <!-- begin wrapper -->
                    <div class="wrapper bg-silver-lighter text-right clearfix">
                        <div class="btn-group btn-toolbar">
                            <a href="{% url 'notifications:home' %}" class="btn btn-white btn-sm disabled"><i class="fa fa-arrow-up"></i></a>
                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-arrow-down"></i></a>
                        </div>
                        <div class="btn-group m-l-5">
                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <!-- end wrapper -->
                </div>
                <!-- end vertical-box-column -->
            </div>
            <!-- end vertical-box -->
</div>
<!-- end row -->
{% endblock %}

{% block lazy_javascript_code %}
<script type="text/javascript">
    
    $.get( "{% url 'notifications:live_all_notification_count' %}", function( data ) {
      $( ".total_msgs" ).html( data.all_count + " message(s)" );
      $( ".all_msgs" ).html( data.all_count );
    });

    
    $.get( "{% url 'notifications:mark_as_read' slug=notification.slug %}", function( data ) {});

</script>

{% endblock %}

notifications/templates/notifications/list.html
{% for notice in notifications %}
{% include 'notifications/message.html' %}
{% endfor %}

notifications/templates/notifications/message.html
<li class="media">
<a href="{% url 'notifications:mark_as_read' notice.slug %}">
    <div class="media-left"><i class="fa fa-envelope media-object bg-blue"></i></div>
    <div class="media-body">
        <h6 class="media-heading">
        	{{ notice.actor }} 
		    {{ notice.verb }}
		    {% if notice.target %}
		      of {{ notice.target }}
		    {% endif %}
		</h6>
        <div class="text-muted f-s-11">{{ notice.timesince }} ago</div>
    </div>
</a>
</li>

notifications/templates/notifications/notice.html
<li class="media">
<div class="alert alert-block alert-{{ notice.level }}">
  <a class="close pull-right" href="{% url 'notifications:mark_as_read' notice.slug %}">
    <i class="icon-close"></i>
  </a>
  
  <h4>
    <i class="icon-mail{% if notice.unread %}-alt{% endif %}"></i>
    {{ notice.actor }} 
    {{ notice.verb }}
    {% if notice.target %}
      of {{ notice.target }}
    {% endif %}
  </h4>
  
  <p>{{ notice.timesince }} ago</p>
  
  <p>{{ notice.description|linebreaksbr }}</p>
  
  <div class="notice-actions">
    {% for action in notice.data.actions %}
      <a class="btn" href="{{ action.href }}">{{ action.title }}</a>
    {% endfor %}
  </div>
</div>
</li>

notifications/templates/notifications/test_tags.html
{% load notifications_tags %}

{% register_notify_callbacks callbacks='fill_notification_menu,fill_notification_badge' %}

{% notifications_unread as unread %}
{{ unread }}
{% live_notify_badge %}
{% live_notify_list %}